# Generated by Django 4.0.4 on 2022-07-06 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Group Name')),
            ],
        ),
        migrations.CreateModel(
            name='PushUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='Identifier')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushuser.pushgroupmodel', verbose_name='Push Group')),
                ('pushUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushuser.pushusermodel', verbose_name='Push User')),
            ],
        ),
    ]
