# Generated by Django 4.0.4 on 2022-07-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(auto_created=True, verbose_name='Add Time')),
                ('title', models.CharField(max_length=130, verbose_name='Title')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
            ],
        ),
    ]
