# Generated by Django 4.0.4 on 2022-07-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushuser', '0002_pushmessagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendDate', models.DateTimeField(blank=True, null=True, verbose_name='Add Date')),
                ('pushGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushuser.pushgroupmodel', verbose_name='Push Group')),
                ('pushMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushuser.pushmessagemodel', verbose_name='Push Message')),
            ],
        ),
    ]
