# Generated by Django 4.0.4 on 2022-07-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushuser', '0003_pushtogroupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmessagemodel',
            name='detail',
            field=models.CharField(default='', max_length=130, verbose_name='Detail (Only Admin See)'),
            preserve_default=False,
        ),
    ]
