# Generated by Django 4.0.4 on 2022-07-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushuser', '0004_pushmessagemodel_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushmessagemodel',
            name='detail',
            field=models.CharField(max_length=130, verbose_name='Detail (Only Admin)'),
        ),
    ]
